### ISSUE TITLE
Error transitioning review period to awaiting review

### ISSUE THREAD

**Issue by mkimberlin** [objectcomputing/check-ins#2579]
**Describe the bug**
In the development environment, an error occurs when moving a review period to Awaiting Approval

**To Reproduce**
1. Make a review new review period
2. Set the required dates
3. Hit the request approval button
4. Watch it go boom...

**Expected behavior**
It doesn't go boom, but rather notifies the supervisors that their attention is required and transitions state as expected

**Screenshots**
```

java.lang.NullPointerException: null
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1715)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.objectcomputing.checkins.services.reviews.ReviewPeriodServicesImpl.notifyRevieweeSupervisorsByReviewPeriod(ReviewPeriodServicesImpl.java:147)
	at com.objectcomputing.checkins.services.reviews.ReviewPeriodServicesImpl.update(ReviewPeriodServicesImpl.java:131)
	at com.objectcomputing.checkins.services.reviews.$ReviewPeriodServicesImpl$Definition$Intercepted.$$access$$update(Unknown Source)
	at com.objectcomputing.checkins.services.reviews.$ReviewPeriodServicesImpl$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:456)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:129)
	at io.micronaut.validation.ValidatingInterceptor.validateReturnMicronautValidator(ValidatingInterceptor.java:153)
	at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:139)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:138)
	at com.objectcomputing.checkins.services.reviews.$ReviewPeriodServicesImpl$Definition$Intercepted.update(Unknown Source)
	at com.objectcomputing.checkins.services.reviews.ReviewPeriodController.update(ReviewPeriodController.java:95)
	at com.objectcomputing.checkins.services.reviews.$ReviewPeriodController$Definition$Intercepted.$$access$$update(Unknown Source)
	at com.objectcomputing.checkins.services.reviews.$ReviewPeriodController$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:456)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:129)
	at io.micronaut.validation.ValidatingInterceptor.validateReturnMicronautValidator(ValidatingInterceptor.java:153)
	at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:139)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:138)
	at com.objectcomputing.checkins.services.reviews.$ReviewPeriodController$Definition$Intercepted.update(Unknown Source)
	at com.objectcomputing.checkins.services.reviews.$ReviewPeriodController$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invokeUnsafe(AbstractExecutableMethodsDefinition.java:461)
	at io.micronaut.context.DefaultBeanContext$BeanContextUnsafeExecutionHandle.invokeUnsafe(DefaultBeanContext.java:4325)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:271)
	at io.micronaut.web.router.DefaultUriRouteMatch.execute(DefaultUriRouteMatch.java:39)
	at io.micronaut.http.server.RouteExecutor.executeRouteAndConvertBody(RouteExecutor.java:490)
	at io.micronaut.http.server.RouteExecutor.lambda$callRoute$6(RouteExecutor.java:467)
	at io.micronaut.core.execution.ExecutionFlow.lambda$async$1(ExecutionFlow.java:87)
	at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211)
	at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211)
	at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:329)
```

**Additional context**
I believe this may be due to a person in the review not having a defined supervisor, but I'm not certain.

**Comment by mkimberlin** [comment]
Verified in dev...thanks @Luch76 !
